In [5]:
import numpy as np
import pandas as pd

In [10]:
import tasks as tsk

ModuleNotFoundError: No module named 'scipy'

In [ ]:
def set_penalty(row, lows, highs):
    if row.place == "cruise ship":
        return tsk.cruise_utility
    elif row.place in lows:
        return tsk.low_penalty
    elif row.place in highs:
        return tsk.high_penalty
    else:
        return row.update_utility


def add_utility(df):
    df["update_utility"] = tsk.standard_penalty
    low = [
        "Plaça de Cort",
        "Plaça de toros de Palma",
        "Plaza Del Mercat",
        "Plaça del Rei Joan Carles I"
    ]
    high = [
        "Catedral-Basílica de Santa María de Mallorca",
        "Castell de Bellver",
        "Royal Palace of La Almudaina",
        "Museu Fundación Juan March, Palma",
        "Museo de Mallorca",
        "Museu Diocesà de Mallorca"
    ]

    df["update_utility"] = df.apply(lambda row: set_penalty(row, low, high), axis=1)

    return df

In [6]:
tasks = pd.read_csv(
        "palmadata/palmapointsofinterest_cleaned.csv",
        header=0,
        dtype={
            "place": 'str',
            "description": 'str',
            "latitude": 'float',
            "longitude": 'float',
            "stars": 'float',
            "reviews": 'float'
        }
    )

In [8]:
tasks.head(5)

,place,description,latitude,longitude,stars,reviews,utility
0,cruise ship,tourist cruise ship,39.568276,2.637640,0.000000,0.0,0.000000
1,Catedral-Basílica de Santa María de Mallorca,Gothic place of worship on the seafront,39.567425,2.648299,4.674750,31176.0,0.951213
2,Castell de Bellver,Hilltop 1300s castle for panoramic views,39.563814,2.619354,4.436243,10446.0,0.749203
3,Royal Palace of La Almudaina,Historic palace of the Royal Family,39.567886,2.647022,4.420346,2310.0,0.681576
4,Tren Soller,Scenic electric railway dating to 1912,39.576665,2.653782,4.396561,5757.0,0.705649

In [9]:
tasks.utility

0     0.000000
1     0.951213
2     0.749203
3     0.681576
4     0.705649
5     0.658831
6     0.805680
7     0.628066
8     0.681866
9     0.110000
10    0.681638
11    0.566864
12    0.770838
13    0.677694
14    0.682884
15    0.676925
16    0.675016
17    0.637629
18    0.666752
19    0.433081
20    0.422808
21    0.661343
22    0.612931
23    0.576082
24    0.604166
25    0.110000
26    0.688986
27    0.110000
28    0.719528
29    0.621275
30    0.689438
31    0.667406
32    0.677208
33    0.110000
34    0.679042
35    0.676551
36    0.693814
37    0.668886
38    0.621541
39    0.110000
40    0.643848
41    0.682518
42    0.605772
43    0.726049
44    0.653099
45    0.618470
46    0.599828
47    0.715489
48    0.671357
49    0.712628
50    0.110000
51    0.110000
52    0.652358
53    0.637564
54    0.645779
55    0.709444
Name: utility, dtype: float64